[
  {
    "task_id": 30,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 38,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 6,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 0,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 47,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 17,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 41,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 2,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 28,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 42,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 15,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 48,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 36,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 8,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 45,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 46,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 25,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 27,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 32,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 21,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 11,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 7,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 16,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 9,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 1,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 3,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 33,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 35,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 14,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 37,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 43,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 40,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 10,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 26,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 22,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 13,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 4,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 12,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 31,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 24,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 56, in solve\n    env_response = env.step(action)\n                   ^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 97, in step\n    observation = self.user.step(action.kwargs[\"content\"])\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 82, in step\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 34,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 39,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 18,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 20,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 5,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 19,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 44,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 23,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 49,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 85, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 46, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  }
]