[
  {
    "task_id": 14,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 9,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 19,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 16,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 5,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 22,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 2,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 1,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 31, in solve\n    env_reset_res = env.reset(task_index=task_index)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/base.py\", line 85, in reset\n    initial_observation = self.user.reset(instruction=self.task.instruction)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 78, in reset\n    return self.generate_next_message(self.messages)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/envs/user.py\", line 47, in generate_next_message\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 13,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 40, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  },
  {
    "task_id": 24,
    "reward": 0.0,
    "info": {
      "error": "cannot schedule new futures after shutdown",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/run.py\", line 82, in _run\n    res = agent.solve(\n          ^^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/tau_bench/agents/tool_calling_agent.py\", line 40, in solve\n    res = completion(\n          ^^^^^^^^^^^\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1285, in wrapper\n    raise e\n  File \"/Users/saumya/ART/dev/tau-bench/.venv/lib/python3.11/site-packages/litellm/utils.py\", line 1216, in wrapper\n    executor.submit(\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py\", line 167, in submit\n    raise RuntimeError('cannot schedule new futures after shutdown')\nRuntimeError: cannot schedule new futures after shutdown\n"
    },
    "traj": [],
    "trial": 0
  }
]